# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AirQualityToolkit.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow,QFileDialog,QMessageBox,QTableWidgetItem

from CSVFormatter import *
from Stitcher import *
from Factorizer import *
from NO2Processor import *
from Statistics_Generator import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 573)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setEnabled(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(25, -1, 25, -1)
        self.gridLayout_2.setHorizontalSpacing(100)
        self.gridLayout_2.setVerticalSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.Stat_Max = QtWidgets.QCheckBox(self.groupBox)
        self.Stat_Max.setChecked(True)
        self.Stat_Max.setObjectName("Stat_Max")
        self.gridLayout_2.addWidget(self.Stat_Max, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Stat_Average = QtWidgets.QCheckBox(self.groupBox)
        self.Stat_Average.setChecked(True)
        self.Stat_Average.setObjectName("Stat_Average")
        self.gridLayout_2.addWidget(self.Stat_Average, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Stat_Max_Average = QtWidgets.QCheckBox(self.groupBox)
        self.Stat_Max_Average.setChecked(True)
        self.Stat_Max_Average.setTristate(False)
        self.Stat_Max_Average.setObjectName("Stat_Max_Average")
        self.gridLayout_2.addWidget(self.Stat_Max_Average, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Stat_Max_Max = QtWidgets.QCheckBox(self.groupBox)
        self.Stat_Max_Max.setChecked(True)
        self.Stat_Max_Max.setObjectName("Stat_Max_Max")
        self.gridLayout_2.addWidget(self.Stat_Max_Max, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Stat_Percentile_En = QtWidgets.QCheckBox(self.groupBox)
        self.Stat_Percentile_En.setObjectName("Stat_Percentile_En")
        self.gridLayout_7.addWidget(self.Stat_Percentile_En, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Stat_Percentile_Max = QtWidgets.QCheckBox(self.groupBox)
        self.Stat_Percentile_Max.setObjectName("Stat_Percentile_Max")
        self.gridLayout_7.addWidget(self.Stat_Percentile_Max, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.gridLayout_7, 3, 2, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Stat_Rolling_En = QtWidgets.QCheckBox(self.groupBox)
        self.Stat_Rolling_En.setObjectName("Stat_Rolling_En")
        self.gridLayout_8.addWidget(self.Stat_Rolling_En, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Stat_Rolling_Max = QtWidgets.QCheckBox(self.groupBox)
        self.Stat_Rolling_Max.setObjectName("Stat_Rolling_Max")
        self.gridLayout_8.addWidget(self.Stat_Rolling_Max, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_2.addLayout(self.gridLayout_8, 4, 2, 1, 1)
        self.Stat_Percentile_Num = QtWidgets.QLineEdit(self.groupBox)
        self.Stat_Percentile_Num.setObjectName("Stat_Percentile_Num")
        self.gridLayout_2.addWidget(self.Stat_Percentile_Num, 3, 1, 1, 1)
        self.Stat_Rolling_Num = QtWidgets.QLineEdit(self.groupBox)
        self.Stat_Rolling_Num.setObjectName("Stat_Rolling_Num")
        self.gridLayout_2.addWidget(self.Stat_Rolling_Num, 4, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(25, 0, 25, 0)
        self.gridLayout.setHorizontalSpacing(100)
        self.gridLayout.setVerticalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Stat_Browse_1 = QtWidgets.QPushButton(self.groupBox)
        self.Stat_Browse_1.setObjectName("Stat_Browse_1")
        self.gridLayout.addWidget(self.Stat_Browse_1, 0, 2, 1, 1)
        self.Stat_Run_1 = QtWidgets.QPushButton(self.groupBox)
        self.Stat_Run_1.setObjectName("Stat_Run_1")
        self.gridLayout.addWidget(self.Stat_Run_1, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.Stat_Header = QtWidgets.QLineEdit(self.groupBox)
        self.Stat_Header.setObjectName("Stat_Header")
        self.gridLayout.addWidget(self.Stat_Header, 1, 1, 1, 1)
        self.Stat_To_Convert = QtWidgets.QLineEdit(self.groupBox)
        self.Stat_To_Convert.setObjectName("Stat_To_Convert")
        self.gridLayout.addWidget(self.Stat_To_Convert, 0, 1, 1, 1)
        self.Stat_Output = QtWidgets.QLineEdit(self.groupBox)
        self.Stat_Output.setObjectName("Stat_Output")
        self.gridLayout.addWidget(self.Stat_Output, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Stitcher_Out_File = QtWidgets.QLineEdit(self.tab_2)
        self.Stitcher_Out_File.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Stitcher_Out_File.setObjectName("Stitcher_Out_File")
        self.gridLayout_6.addWidget(self.Stitcher_Out_File, 1, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.Stitcher_Out_Folder = QtWidgets.QLineEdit(self.tab_2)
        self.Stitcher_Out_Folder.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Stitcher_Out_Folder.setObjectName("Stitcher_Out_Folder")
        self.gridLayout_6.addWidget(self.Stitcher_Out_Folder, 1, 1, 1, 1)
        self.Stitcher_Import = QtWidgets.QPushButton(self.tab_2)
        self.Stitcher_Import.setObjectName("Stitcher_Import")
        self.gridLayout_6.addWidget(self.Stitcher_Import, 0, 1, 1, 1)
        self.Stitcher_Clear = QtWidgets.QPushButton(self.tab_2)
        self.Stitcher_Clear.setObjectName("Stitcher_Clear")
        self.gridLayout_6.addWidget(self.Stitcher_Clear, 0, 2, 1, 1)
        self.Stitcher_Run = QtWidgets.QPushButton(self.tab_2)
        self.Stitcher_Run.setObjectName("Stitcher_Run")
        self.gridLayout_6.addWidget(self.Stitcher_Run, 0, 3, 1, 1)
        self.Stitcher_Browse = QtWidgets.QPushButton(self.tab_2)
        self.Stitcher_Browse.setObjectName("Stitcher_Browse")
        self.gridLayout_6.addWidget(self.Stitcher_Browse, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_5.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.Stitcher_Table = QtWidgets.QTableWidget(self.tab_2)
        self.Stitcher_Table.setRowCount(5)
        self.Stitcher_Table.setObjectName("Stitcher_Table")
        self.Stitcher_Table.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.Stitcher_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Stitcher_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Stitcher_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Stitcher_Table.setHorizontalHeaderItem(3, item)
        self.Stitcher_Table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_5.addWidget(self.Stitcher_Table, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_15.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_18.addWidget(self.lineEdit_15, 1, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_18.addWidget(self.label_17, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_16.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_18.addWidget(self.lineEdit_16, 1, 1, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_18.addWidget(self.pushButton_13, 0, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_18.addWidget(self.pushButton_14, 0, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_18.addWidget(self.pushButton_15, 0, 3, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_18.addWidget(self.pushButton_16, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_18.addWidget(self.label_18, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_19.addLayout(self.gridLayout_18, 1, 1, 1, 1)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setRowCount(5)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_19.addWidget(self.tableWidget_3, 0, 0, 1, 2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_20.addWidget(self.pushButton_19, 0, 3, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_20.addWidget(self.pushButton_17, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_7)
        self.label_19.setObjectName("label_19")
        self.gridLayout_20.addWidget(self.label_19, 1, 2, 1, 1, QtCore.Qt.AlignRight)
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_20.addWidget(self.pushButton_18, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_7)
        self.label_20.setObjectName("label_20")
        self.gridLayout_20.addWidget(self.label_20, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_20.addWidget(self.pushButton_20, 0, 0, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_17.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_20.addWidget(self.lineEdit_17, 1, 3, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_18.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_20.addWidget(self.lineEdit_18, 1, 1, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_20, 1, 0, 1, 1)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_4.setRowCount(5)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(259)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_21.addWidget(self.tableWidget_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.tab_8)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.gridLayout_26 = QtWidgets.QGridLayout()
        self.gridLayout_26.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_26.setContentsMargins(25, 0, 25, 0)
        self.gridLayout_26.setHorizontalSpacing(100)
        self.gridLayout_26.setVerticalSpacing(7)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_26.addWidget(self.label_24, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_26.addWidget(self.label_25, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_26.addWidget(self.pushButton_21, 0, 2, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_26.addWidget(self.lineEdit_21, 1, 1, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_26.addWidget(self.lineEdit_22, 0, 1, 1, 1)
        self.checkBox_25 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_25.setObjectName("checkBox_25")
        self.gridLayout_26.addWidget(self.checkBox_25, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_26.addWidget(self.pushButton_22, 1, 2, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_26, 1, 0, 1, 1)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setContentsMargins(25, -1, 25, -1)
        self.gridLayout_23.setHorizontalSpacing(100)
        self.gridLayout_23.setVerticalSpacing(7)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_23.addWidget(self.pushButton_23, 0, 2, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_23.addWidget(self.pushButton_24, 1, 2, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_23.addWidget(self.lineEdit_24, 1, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_23.addWidget(self.label_26, 0, 0, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_23.addWidget(self.lineEdit_19, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_23.addWidget(self.label_22, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_23.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_23.addWidget(self.label_23, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_23.addWidget(self.lineEdit_23, 0, 1, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_23.addWidget(self.lineEdit_20, 3, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setObjectName("label_27")
        self.gridLayout_23.addWidget(self.label_27, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setObjectName("label_28")
        self.gridLayout_23.addWidget(self.label_28, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_23.addWidget(self.lineEdit_25, 4, 1, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_23.addWidget(self.lineEdit_26, 5, 1, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_23.addWidget(self.pushButton_25, 5, 2, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_23, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_22.addWidget(self.line, 2, 0, 1, 1)
        self.gridLayout_27.addWidget(self.groupBox_3, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_27.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_27.addItem(spacerItem2, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_8, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 996, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Statistics Tools"))
        self.label_4.setText(_translate("MainWindow", "Settings for Statistics"))
        self.Stat_Max.setText(_translate("MainWindow", "Max of Sensor"))
        self.label_5.setText(_translate("MainWindow", "Percentile to compute (eg 99.9)"))
        self.Stat_Average.setText(_translate("MainWindow", "Average of Sensor"))
        self.Stat_Max_Average.setText(_translate("MainWindow", "Max Average of Sensors"))
        self.label_6.setText(_translate("MainWindow", "Rolling average window (eg 8)"))
        self.Stat_Max_Max.setText(_translate("MainWindow", "Max of All Sensors"))
        self.Stat_Percentile_En.setText(_translate("MainWindow", "Enable Percentile"))
        self.Stat_Percentile_Max.setText(_translate("MainWindow", "Max of Percentile"))
        self.Stat_Rolling_En.setText(_translate("MainWindow", "Enable Rolling"))
        self.Stat_Rolling_Max.setText(_translate("MainWindow", "Max of Rolling"))
        self.label.setText(_translate("MainWindow", "Filename of CSV to process:"))
        self.label_2.setText(_translate("MainWindow", "Number of header columns in dataset (eg 3):"))
        self.Stat_Browse_1.setText(_translate("MainWindow", "Browse"))
        self.Stat_Run_1.setText(_translate("MainWindow", "Run"))
        self.label_3.setText(_translate("MainWindow", "File name of output statistics CSV:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Statistics Generator"))
        self.label_7.setText(_translate("MainWindow", "Output File Name:"))
        self.Stitcher_Import.setText(_translate("MainWindow", "Import Settings CSV"))
        self.Stitcher_Clear.setText(_translate("MainWindow", "Clear"))
        self.Stitcher_Run.setText(_translate("MainWindow", "Stitch"))
        self.Stitcher_Browse.setText(_translate("MainWindow", "Browse"))
        self.label_8.setText(_translate("MainWindow", "Output Folder:"))
        item = self.Stitcher_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Folder"))
        item = self.Stitcher_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.Stitcher_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Scale"))
        item = self.Stitcher_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Columns to Exclude"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Stitcher"))
        self.label_17.setText(_translate("MainWindow", "Output File Name:"))
        self.pushButton_13.setText(_translate("MainWindow", "Import Settings CSV"))
        self.pushButton_14.setText(_translate("MainWindow", "Clear"))
        self.pushButton_15.setText(_translate("MainWindow", "Factorize"))
        self.pushButton_16.setText(_translate("MainWindow", "Browse"))
        self.label_18.setText(_translate("MainWindow", "Output Folder:"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Factor"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Output File Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Factorizer"))
        self.pushButton_19.setText(_translate("MainWindow", "Convert"))
        self.pushButton_17.setText(_translate("MainWindow", "Import Settings CSV"))
        self.label_19.setText(_translate("MainWindow", "Output File Name:"))
        self.pushButton_18.setText(_translate("MainWindow", "Clear"))
        self.label_20.setText(_translate("MainWindow", "Output Folder:"))
        self.pushButton_20.setText(_translate("MainWindow", "Browse"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "File Name"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CALPUFF Output Format? (0/1)"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Output File Name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "Mass CSV Formatter"))
        self.groupBox_3.setTitle(_translate("MainWindow", "NO2 Processor Tools"))
        self.label_24.setText(_translate("MainWindow", "File to format as CSV:"))
        self.label_25.setText(_translate("MainWindow", "File name of output CSV:"))
        self.pushButton_21.setText(_translate("MainWindow", "Browse"))
        self.checkBox_25.setText(_translate("MainWindow", "CALPUFF Output Format?"))
        self.pushButton_22.setText(_translate("MainWindow", "Convert to CSV"))
        self.pushButton_23.setText(_translate("MainWindow", "Browse"))
        self.pushButton_24.setText(_translate("MainWindow", "Browse"))
        self.label_26.setText(_translate("MainWindow", "File name of CSV to process:"))
        self.lineEdit_19.setText(_translate("MainWindow", "0.1"))
        self.label_22.setText(_translate("MainWindow", "Initial % to process (eg 0.1)"))
        self.label_21.setText(_translate("MainWindow", "File name of Background NO2 CSV:"))
        self.label_23.setText(_translate("MainWindow", "Number of exceedances limit (eg 246)"))
        self.lineEdit_20.setText(_translate("MainWindow", "246"))
        self.label_27.setText(_translate("MainWindow", "Number of header columns in dataset (eg 3)"))
        self.label_28.setText(_translate("MainWindow", "File name of output statistics CSV:"))
        self.lineEdit_25.setText(_translate("MainWindow", "3"))
        self.pushButton_25.setText(_translate("MainWindow", "Process CSV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "NO2 Processor"))

        #STATISTICS BUTTONS
        self.Stat_Browse_1.clicked.connect(self.Stat_Browse_Clicked)
        self.Stat_Run_1.clicked.connect(self.Stat_Run_Clicked)

        #STITCHER BUTTONS
        self.Stitcher_Browse.clicked.connect(self.Stitcher_Browse_Clicked)


#### STATISTICS GENERATOR FUNCTIONS
    @staticmethod
    def ErrorBox(errortext,console_error):
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText(errortext)
            msg.setWindowTitle("Error")
            msg.setInformativeText("Please review input settings")
            msg.setDetailedText("Error from console: \n" + console_error)
            msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
            msg.exec_()

    def Stat_Browse_Clicked(self):
        self.Stat_To_Convert.setText("")
        self.Stat_Output.setText("")
        options = QFileDialog.Options()
        # options |= QFileDialog.DontUseNativeDialog
        filename,_ = QFileDialog.getOpenFileNames(None,"CSV File to Process","","CSV Files (*.csv);;All Files (*);", options=options)
        self.Stat_To_Convert.setText(filename[0])
        self.Stat_Output.setText(filename[0].split('.')[0]+ "_Statistics.csv")

    def Stat_Run_Clicked(self):
        settings = {}
        settings['mean'] = self.Stat_Average.isChecked()
        settings['max_of_sensor'] = self.Stat_Max.isChecked()
        settings['max_mean'] = self.Stat_Max_Average.isChecked()
        settings['max'] = self.Stat_Max_Max.isChecked()
        settings['percentile'] = self.Stat_Percentile_En.isChecked()
        if self.Stat_Percentile_En.isChecked():
            settings['percentile_value'] = float(self.Stat_Percentile_Num.text()) / 100
        settings['max_percentile'] = self.Stat_Percentile_Max.isChecked()
        settings['rolling'] = self.Stat_Rolling_En.isChecked()
        if self.Stat_Rolling_En.isChecked():
            settings['rolling_value'] = int(self.Stat_Rolling_Num.text())
        settings['max_rolling'] = self.Stat_Rolling_Max.isChecked()
        try:
            Statistics_Generator(settings,self.Stat_Header.text(),self.Stat_To_Convert.text(),self.Stat_Output.text())
        except ValueError as error:
            self.ErrorBox("Input Settings Invalid",str(error))
            raise


#### STITCHER FUNCTIONS

    def Stitcher_Browse_Clicked(self):
        options = QFileDialog.Options()
        filename,_ = QFileDialog.getOpenFileNames(None,"CSV File to Process","","CSV Files (*.csv);;All Files (*);", options=options)
        stitcher_tbl = []
        for row in range(self.Stitcher_Table.rowCount()):
            stitcher_tbl.append([])
            for col in range(self.Stitcher_Table.columnCount()):
                value = self.Stitcher_Table.item(row,col)
                print(value)
                stitcher_tbl[row].append(str(value))
        print(stitcher_tbl)
        self.Stitcher_Table.setItem(0,0,QTableWidgetItem(filename[0]))







